import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/carrusel.module.css'
import Image from '../pages/component/image'


const inter = Inter({ subsets: ['latin'] })

const myLoader = ({ src, width, quality }) => {
  return `https://example.com/${src}?w=${width}&q=${quality || 75}`
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Carrusel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
          <div className={styles.conteudo}>
            <Image />
        </div>
    </>
  )
}
